# Generated by Django 5.0.7 on 2024-08-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp', '0012_alter_expert_id'),
        ('skills', '0006_alter_skill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number_of_participants', models.PositiveIntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.expert')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
        ),
    ]
