# Generated by Django 5.0.7 on 2024-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_training_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
