# Generated by Django 5.0.7 on 2024-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_delete_item_delete_todolist'),
    ]

    operations = [
    ]
