# Generated by Django 5.0.7 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='skill',
            field=models.CharField(max_length=20),
        ),
    ]
