# Generated by Django 5.0.7 on 2024-08-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_alter_expert_skill'),
        ('skills', '0003_auto_20240806_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='skill_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='skill',
            field=models.CharField(max_length=20),
        ),
    ]
