# Generated by Django 5.0.7 on 2024-08-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_expert_skill_id_alter_expert_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='skill_id',
        ),
    ]
