# Generated by Django 5.0.7 on 2024-08-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_remove_expert_skill_id'),
        ('skills', '0003_auto_20240806_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='skill_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
