# Generated by Django 5.0.7 on 2024-08-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0007_alter_expert_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='skill',
        ),
    ]
