# Generated by Django 5.0.7 on 2024-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_remove_expert_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='skill',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
