# Generated by Django 5.0.7 on 2024-08-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0009_expert_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='skill',
        ),
    ]
