# Generated by Django 5.0.7 on 2024-08-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0010_remove_expert_skill'),
        ('skills', '0006_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='skill_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
