# Generated by Django 5.0.7 on 2024-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0011_alter_expert_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
