# Generated by Django 5.0.7 on 2024-08-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='t', max_length=255),
            preserve_default=False,
        ),
    ]
